#!/usr/bin/env bash

set -e

# Change these paths:
# Path to intellij sources. Snapshot will be placed in the "snapshots" subdirectory.
INTELLIJ=$HOME/intellij
# Path to the Kotlin compiler which will be used for the build.
KOTLIN_COMPILER=$HOME/kotlin/dist/kotlinc
# Path to the Kotlin IDE plugin which will be used for the build.
# NOTE that the compiler inside it will be REPLACED with the compiler specified above.
# TODO: get rid of this, use JPS plugin built in main Kotlin repo.
KOTLIN_PLUGIN_HOME=$HOME/.local/share/JetBrains/IntelliJIdea2021.2/Kotlin
# Path to IntelliJ IDEA which will be used for the build (Groovy plugin will be loaded from here).
IDEA_HOME=$HOME/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5457.46
# JDK which will be used for the build. Note that IntelliJ build requires JDK 11.
JAVA=/usr/lib/jvm/java-11-microsoft

# Uncomment to compile a single module with its dependencies.
BUILD_MODULE=-Dbuild.moduleName=intellij.platform.util.rt

SNAPSHOT_TEMPORARY_OUTPUT=$INTELLIJ/snapshots/snapshot.collapsed
SNAPSHOT=-agentpath:$HOME/async-profiler/build/libasyncProfiler.so=start\,event=cpu\,interval=10ms\,threads\,file=$SNAPSHOT_TEMPORARY_OUTPUT

JPS_CLASSPATH=$(mvn -q -f jps-wrapper-classpath.xml dependency:build-classpath -Dmdep.outputFile=/tmp/idea-jps-classpath.txt && cat /tmp/idea-jps-classpath.txt)
KOTLIN_JPS_PLUGIN=$KOTLIN_PLUGIN_HOME/lib/jps/kotlin-jps-plugin.jar:$KOTLIN_PLUGIN_HOME/lib/kotlin-reflect.jar:$KOTLIN_PLUGIN_HOME/lib/kotlin-common.jar:$(echo $KOTLIN_PLUGIN_HOME/lib/kotlin-compiler-common-for-ide-*.jar):$(echo $KOTLIN_PLUGIN_HOME/lib/kotlin-compiler-fe10-for-ide-*.jar)
GROOVY_JPS_PLUGIN=$IDEA_HOME/plugins/Groovy/lib/groovy-jps.jar:$IDEA_HOME/plugins/Groovy/lib/groovy-constants-rt.jar
OUTPUT=$(dirname "$(realpath -s "$0")")/out
rm -rf $OUTPUT && mkdir $OUTPUT
mkdir -p $INTELLIJ/snapshots

time taskset 0xFF000000 $JAVA/bin/java \
    -Xmx12G $SNAPSHOT \
    -Dgroovyc.in.process=true \
    -Dgroovyc.asm.resolving.only=false \
    -Djps.use.default.file.logging=false \
    -Didea.home.path=. \
    -Dbuild.incremental=false \
    -Dbuild.parallel=true \
    -Dbuild.withProgress=true \
    -Dbuild.includeRuntimeDependencies=false \
    -Dbuild.includeTests=true \
    -Dbuild.kotlinHome=$KOTLIN_PLUGIN_HOME \
    -Dbuild.projectPath=$INTELLIJ \
    -Dbuild.outputPath=$OUTPUT \
    -Dbuild.classpathOutputFilePath=$OUTPUT/classpath.txt \
    $BUILD_MODULE \
    -Dfile.encoding=UTF-8 \
    -classpath $JPS_CLASSPATH:$KOTLIN_JPS_PLUGIN:$GROOVY_JPS_PLUGIN \
    jps.wrapper.MainKt \
    >$OUTPUT/log.txt 2>&1

if [[ -n "$SNAPSHOT" ]]; then
    SNAPSHOT_NAME=$1
    SNAPSHOT_NAME=${SNAPSHOT_NAME:-snapshot}
    RESULT=$INTELLIJ/snapshots/$SNAPSHOT_NAME.zip
    $KOTLIN_COMPILER/bin/kotlinc -script ../preprocess-snapshot.kts -- $RESULT $SNAPSHOT_TEMPORARY_OUTPUT
    rm $SNAPSHOT_TEMPORARY_OUTPUT
    echo "snapshot: $RESULT"
fi
